---
- name: Ensure monitoring stack directory exists
  ansible.builtin.file:
    path: "{{ monitoring_stack_app_dir }}"
    state: directory
    mode: "{{ monitoring_stack_dir_mode }}"

- name: Copy monitoring stack files
  ansible.builtin.copy:
    src: "{{ monitoring_stack_source_dir }}/"
    dest: "{{ monitoring_stack_app_dir }}/"
    mode: "{{ monitoring_stack_file_mode }}"

- name: Ensure monitoring stack is running with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_stack_app_dir }}"
    state: present
    docker_cli: "{{ monitoring_stack_docker_cli_path }}"
